import type { Metadata } from "next";
import "@/app/globals.css";

import { AppSidebar } from "@/components/route/admin/menu/menu";
import { SidebarInset } from "@/components/ui/sidebar";
import ReduxComponent from "@/components/route/admin/redux-component";
import { ToastContainer } from "react-toastify";
import { getToken } from "@/service/user-service";
import { parseJwt } from "@/util/parse-jwt";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App2",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = await getToken();
  const jwt = parseJwt(token);
  if (!jwt || jwt.role == "user") {
    redirect("/");
  }

  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/4.6.0/remixicon.css"
          integrity="sha512-kJlvECunwXftkPwyvHbclArO8wszgBGisiLeuDFwNM8ws+wKIw0sv1os3ClWZOcrEB2eRXULYUsm8OVRGJKwGA=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        ></link>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700&display=swap"
        />
      </head>
      <body className=" overflow-x-hidden">
        <div className=" mx-auto">
          <ToastContainer />
          <ReduxComponent
            children={
              <>
                <AppSidebar {...jwt} />
                <SidebarInset>
                  <main className="bg-[#F1F1F1]">
                    <section>{children}</section>
                    <footer className="h-100"></footer>
                  </main>
                </SidebarInset>
              </>
            }
          />
        </div>
      </body>
    </html>
  );
}
